services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecometrics_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ecometrics
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: ecometrics_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ecometrics
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: ecometrics_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecometrics
      POSTGRES_USER: ecometrics
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - ecometrics

  redis:
    image: redis:7-alpine
    container_name: ecometrics_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ecometrics

networks:
  ecometrics:
    driver: bridge

volumes:
  dbdata: